language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: required

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "S190W5bNgSM35uMwyHrUM4/5ipE1SemyfcjGQyRAVtcuQwAug/P5P5wDPrPeQyzgV7c5nDkxjBBr9pJ6xUG3dkPgiqTxchBeccishuMmUUs8pO1kd/o+DEJ3IoZyL5benFZyvTKGaSrZncqlHz0T/tARBQXiK7/ziAZ/qgtsyzXojRXD6Ro8BflphqhsZhpM45MesTSCr7oBfTryq9C6a6NBI7kByw01OpQWYh3F5EG/wEFTIR9gmcCUQzi4SHv9HixRAqjIKbdH1/4QQUVKJsQVvXbYDNbnrmw4scUJGwvFTx5sagLbnEuVGZ7o8ZA6DvUNWWFeaRft9V2NhJRu0hNO69DfyE/16CVqLLv8cSsM5BnMxU43NfzpPw2KkBg55QSLK7j53Tsy7WOSqSgx11Fek1E+TyyuVLLJAlQLuk7+mZBFlGXfMaU17DfFdUO+mZ4F+Bsa1OcTVABl1MmXnhntYADEBQ6bXrDk0I4GXNQ3xCklYGfKt8mbsb8gNRIJIkyRnYDLVB7lkXcMOL25DGORGftrSApQH7q1MRc8bLMtTcXdr+NZioOFrr1UgxQPgOfIEVZ2YepMw2sc0pkfYRWobm8zcIAjpJNPbM7JUYnlYi96OOFsabW4W3IisdPEA8mq8ALlS3kYpwN0jhBt+7/nPAwD8igRAOvjYoIU3t0="
    - GIT_COMMITTER_NAME=akagane99
    - GIT_COMMITTER_EMAIL=akagane99@gmail.com
    - GIT_AUTHOR_NAME=akagane99
    - GIT_AUTHOR_EMAIL=akagane99@gmail.com

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  -  . tools/build/plugins/cakephp/travis/pre.sh

script:
  - travis_wait . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
